package lexicalAnalyzer;

/**
 * States defined in DFA transition table
 */
public enum State {
  INIT, I, IN, INT, IF, C, CL, CLA, CLAS, CLASS, CH, CHA, CHAR, S, ST, STR, STRI, STRIN, STRING, B, BO, BOO, BOOL, BOOLE, BOOLEA, BOOLEAN, W, WH, WHI, WHIL, WHILE, E, EL, ELS, ELSE, R, RE, RET, RETU, RETUR, RETURN, T, TR, TRU, V_BOOLEAN, F, FA, FAL, FALS, PLUS, MINUS, MUL, DIV, LESS, LESS_EQ, GREAT, GREAT_EQ, ASSIGN, EQUAL, EXCLAM, UNEQUAL, SEMICOLON, L_B, R_B, L_M, R_M, L_S, R_S, COMMA, ID, V_INT_ZERO, V_INT, V_STRING1, V_STRING2, V_STRING, V_CHAR1, V_CHAR2, V_CHAR
}
